services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hasznaltauto-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Asd123
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  hasznaltauto.api:
    image: ${DOCKER_REGISTRY-}hasznaltautoapi
    container_name: hasznaltauto-api
    build:
      context: .
      dockerfile: HasznaltAuto.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__HasznaltAutoDbContext=Server=mssql,1433;Database=HasznaltAutoDb;User Id=sa;Password=Admin123;TrustServerCertificate=True
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  mssql-data: